import { StyleSheet } from "react-native";

import { colors } from "@/utils/colors";

export const styles = StyleSheet.create({
  actionBody: {
    flex: 1,
  },
  actionIcon: {
    alignItems: "center",
    backgroundColor: colors.infoSoft,
    borderRadius: 18,
    height: 36,
    justifyContent: "center",
    width: 36,
  },
  actionItem: {
    backgroundColor: colors.panel,
    borderColor: colors.line,
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: "row",
    gap: 12,
    padding: 14,
  },
  actionMessage: {
    color: "#263244",
    fontSize: 14,
    lineHeight: 20,
    marginTop: 6,
  },
  actionRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 16,
  },
  actionTime: {
    color: colors.muted,
    fontSize: 12,
  },
  actionType: {
    color: colors.ink,
    fontSize: 13,
    fontWeight: "800",
  },
  centerState: {
    alignItems: "center",
    flex: 1,
    gap: 12,
    justifyContent: "center",
    padding: 32,
  },
  centerText: {
    color: colors.textSoft,
    fontSize: 15,
  },
  challengeMarker: {
    alignItems: "center",
    borderColor: colors.panel,
    borderRadius: 15,
    borderWidth: 2,
    height: 30,
    justifyContent: "center",
    shadowColor: "#000000",
    shadowOpacity: 0.2,
    shadowRadius: 5,
    width: 30,
  },
  challengeMarkerText: {
    color: colors.panel,
    fontSize: 11,
    fontWeight: "900",
  },
  challengeStatus: {
    fontSize: 13,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  chipBreakdown: {
    gap: 8,
    marginBottom: 16,
  },
  chipInput: {
    backgroundColor: colors.panel,
    borderColor: colors.lineStrong,
    borderRadius: 8,
    borderWidth: 1,
    color: colors.ink,
    flex: 1,
    fontSize: 20,
    fontWeight: "800",
    minHeight: 48,
    textAlign: "center",
  },
  chipLine: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
  },
  chipText: {
    color: colors.text,
    flex: 1,
    fontSize: 14,
  },
  chipValue: {
    color: colors.ink,
    fontSize: 14,
    fontWeight: "800",
  },
  coinText: {
    color: colors.info,
    fontSize: 15,
    fontWeight: "900",
  },
  content: {
    padding: 16,
    paddingBottom: 32,
  },
  description: {
    color: colors.text,
    fontSize: 15,
    lineHeight: 22,
    marginBottom: 16,
  },
  detailsPanel: {
    marginTop: 12,
  },
  disabledButton: {
    opacity: 0.55,
  },
  emptyText: {
    color: colors.muted,
    fontSize: 14,
    lineHeight: 20,
  },
  errorText: {
    color: colors.danger,
    fontSize: 15,
    lineHeight: 21,
    textAlign: "center",
  },
  formLabel: {
    color: colors.textSoft,
    fontSize: 12,
    fontWeight: "800",
    marginBottom: 8,
    marginTop: 4,
    textTransform: "uppercase",
  },
  gameIdInput: {
    backgroundColor: colors.panel,
    borderColor: colors.lineStrong,
    borderRadius: 8,
    borderWidth: 1,
    color: colors.ink,
    fontSize: 13,
    marginTop: 12,
    minHeight: 42,
    paddingHorizontal: 12,
  },
  header: {
    backgroundColor: colors.page,
    borderBottomColor: "#dce3ee",
    borderBottomWidth: 1,
    padding: 16,
    paddingTop: 10,
  },
  headerActions: {
    flexDirection: "row",
    gap: 8,
  },
  headerBackButton: {
    marginRight: 10,
  },
  headerTop: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  iconButton: {
    alignItems: "center",
    backgroundColor: colors.panel,
    borderColor: colors.lineStrong,
    borderRadius: 8,
    borderWidth: 1,
    height: 42,
    justifyContent: "center",
    width: 42,
  },
  iconButtonActive: {
    backgroundColor: colors.info,
    borderColor: colors.info,
  },
  inlineError: {
    backgroundColor: colors.dangerSurface,
    borderColor: colors.dangerSurfaceBorder,
    borderRadius: 8,
    borderWidth: 1,
    color: colors.danger,
    fontSize: 13,
    lineHeight: 18,
    marginBottom: 12,
    padding: 10,
  },
  keyboardAvoidingView: {
    flex: 1,
  },
  kicker: {
    color: colors.info,
    fontSize: 12,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  legendDot: {
    borderRadius: 6,
    height: 12,
    width: 12,
  },
  legendItem: {
    alignItems: "center",
    backgroundColor: colors.panel,
    borderColor: "#dfe6ef",
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: "row",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  legendRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
    paddingRight: 16,
  },
  legendScroller: {
    flexGrow: 0,
    flexShrink: 0,
  },
  legendText: {
    color: colors.text,
    fontSize: 12,
    fontWeight: "700",
  },
  mapFrame: {
    alignSelf: "center",
    backgroundColor: "#d9e6f2",
    borderColor: "#c9d5e5",
    borderRadius: 8,
    borderWidth: 1,
    overflow: "hidden",
  },
  mapImage: {
    left: 0,
    position: "absolute",
    top: 0,
  },
  mapContent: {
    flex: 1,
    overflow: "hidden",
    padding: 16,
  },
  mapInspectorContent: {
    gap: 10,
    paddingBottom: 4,
  },
  mapInspectorScroller: {
    flex: 1,
  },
  mapInspectorShell: {
    flexShrink: 0,
    minHeight: 0,
    overflow: "hidden",
  },
  mapInspectorShellCompact: {
    height: 260,
  },
  mapInspectorShellWide: {
    alignSelf: "stretch",
    width: 360,
  },
  mapLegendSlot: {
    flexShrink: 0,
    height: 38,
    justifyContent: "center",
    overflow: "hidden",
  },
  mapMainPane: {
    flex: 1,
    gap: 12,
    minHeight: 0,
  },
  mapTransformLayer: {
    alignSelf: "center",
  },
  mapViewport: {
    alignItems: "center",
    alignSelf: "center",
    backgroundColor: "#d9e6f2",
    borderColor: "#c9d5e5",
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    justifyContent: "center",
    minHeight: 180,
    overflow: "hidden",
    width: "100%",
  },
  mapViewportSlot: {
    flex: 1,
    minHeight: 0,
  },
  mapWorkspace: {
    flex: 1,
    gap: 12,
    minHeight: 0,
  },
  mapWorkspaceWide: {
    flexDirection: "row",
  },
  colorSwatch: {
    borderColor: colors.panel,
    borderRadius: 8,
    borderWidth: 2,
    height: 36,
    width: 36,
  },
  colorSwatchRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 4,
  },
  colorSwatchSelected: {
    borderColor: colors.ink,
  },
  markerSelected: {
    borderColor: colors.ink,
    borderWidth: 3,
    transform: [{ scale: 1.18 }],
  },
  markerSelectedTarget: {
    zIndex: 5,
  },
  markerTouchTarget: {
    alignItems: "center",
    height: 44,
    justifyContent: "center",
    marginLeft: -22,
    marginTop: -22,
    position: "absolute",
    width: 44,
  },
  metaRow: {
    flexDirection: "row",
    gap: 8,
    marginTop: 12,
  },
  menuButton: {
    alignItems: "center",
    backgroundColor: colors.info,
    borderRadius: 8,
    flexDirection: "row",
    gap: 8,
    justifyContent: "center",
    minHeight: 54,
    paddingHorizontal: 16,
  },
  menuButtonStack: {
    gap: 10,
  },
  menuInput: {
    backgroundColor: colors.panel,
    borderColor: colors.lineStrong,
    borderRadius: 8,
    borderWidth: 1,
    color: colors.ink,
    fontSize: 15,
    minHeight: 46,
    paddingHorizontal: 12,
  },
  menuListItem: {
    alignItems: "center",
    backgroundColor: colors.panel,
    borderColor: colors.line,
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: "row",
    gap: 12,
    padding: 14,
  },
  panel: {
    backgroundColor: colors.panel,
    borderColor: colors.line,
    borderRadius: 8,
    borderWidth: 1,
    padding: 16,
  },
  panelHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  panelTitle: {
    color: colors.ink,
    flex: 1,
    fontSize: 20,
    fontWeight: "900",
    marginBottom: 10,
  },
  pill: {
    backgroundColor: colors.panel,
    borderColor: "#dfe6ef",
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    minHeight: 52,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  pillLabel: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  pillValue: {
    color: colors.ink,
    fontSize: 13,
    fontWeight: "800",
    marginTop: 4,
  },
  primaryButton: {
    alignItems: "center",
    backgroundColor: colors.info,
    borderRadius: 8,
    flex: 1,
    flexDirection: "row",
    gap: 7,
    justifyContent: "center",
    minHeight: 48,
    paddingHorizontal: 14,
  },
  primaryButtonText: {
    color: colors.panel,
    fontSize: 15,
    fontWeight: "900",
  },
  safeArea: {
    backgroundColor: colors.page,
    flex: 1,
  },
  screenStack: {
    gap: 14,
  },
  secondaryButton: {
    alignItems: "center",
    backgroundColor: colors.dangerSoft,
    borderColor: colors.dangerSoftBorder,
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    flexDirection: "row",
    gap: 7,
    justifyContent: "center",
    minHeight: 48,
    paddingHorizontal: 14,
  },
  secondaryButtonText: {
    color: colors.danger,
    fontSize: 15,
    fontWeight: "900",
  },
  selectorRow: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 14,
    paddingRight: 16,
  },
  setupCoordinateInput: {
    flex: 1,
  },
  setupCoordinateRow: {
    flexDirection: "row",
    gap: 8,
  },
  setupDescriptionInput: {
    minHeight: 78,
    paddingTop: 12,
    textAlignVertical: "top",
  },
  setupSection: {
    borderTopColor: colors.line,
    borderTopWidth: 1,
    gap: 10,
    paddingTop: 12,
  },
  stat: {
    backgroundColor: colors.softPanel,
    borderColor: colors.line,
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    padding: 12,
  },
  statGrid: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 16,
  },
  statLabel: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  statValue: {
    color: colors.ink,
    fontSize: 16,
    fontWeight: "900",
    marginTop: 5,
  },
  stationList: {
    color: colors.text,
    fontSize: 14,
    lineHeight: 20,
  },
  stationMarker: {
    borderColor: colors.panel,
    borderRadius: 8,
    borderWidth: 2,
    height: 16,
    shadowColor: "#000000",
    shadowOpacity: 0.22,
    shadowRadius: 4,
    width: 16,
  },
  stationOwnerBadge: {
    alignItems: "center",
    backgroundColor: colors.softPanel,
    borderRadius: 8,
    flexDirection: "row",
    gap: 6,
    marginBottom: 10,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  stationOwnerText: {
    color: colors.text,
    fontSize: 12,
    fontWeight: "800",
  },
  stationPickerOption: {
    alignItems: "center",
    backgroundColor: colors.softPanel,
    borderColor: colors.line,
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: "row",
    gap: 8,
    minHeight: 40,
    paddingHorizontal: 10,
  },
  stationPickerOptionSelected: {
    borderColor: colors.ink,
    borderWidth: 2,
  },
  stationPickerOptionText: {
    color: colors.ink,
    flex: 1,
    fontSize: 13,
    fontWeight: "800",
  },
  stationPickerPanel: {
    backgroundColor: colors.panel,
    borderColor: colors.line,
    borderRadius: 8,
    borderWidth: 1,
    gap: 8,
    marginBottom: 10,
    padding: 12,
  },
  stationPickerTitle: {
    color: colors.textSoft,
    fontSize: 12,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  stepperButton: {
    alignItems: "center",
    backgroundColor: colors.panel,
    borderColor: colors.lineStrong,
    borderRadius: 8,
    borderWidth: 1,
    height: 48,
    justifyContent: "center",
    width: 52,
  },
  stepperNumberInput: {
    flexGrow: 0,
    flexShrink: 1,
    maxWidth: 92,
    minWidth: 64,
  },
  stepperRow: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 14,
  },
  tabBar: {
    backgroundColor: "#eef3f8",
    flexDirection: "row",
    gap: 8,
    padding: 10,
  },
  tabButton: {
    alignItems: "center",
    borderRadius: 8,
    flex: 1,
    flexDirection: "row",
    gap: 6,
    justifyContent: "center",
    minHeight: 42,
  },
  tabButtonActive: {
    backgroundColor: colors.info,
  },
  tabText: {
    color: colors.textSoft,
    fontSize: 14,
    fontWeight: "900",
  },
  tabTextActive: {
    color: colors.panel,
  },
  teamCard: {
    backgroundColor: colors.panel,
    borderColor: colors.line,
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: "row",
    overflow: "hidden",
  },
  teamCardBody: {
    flex: 1,
    padding: 14,
  },
  teamColorBar: {
    width: 8,
  },
  teamDraftCard: {
    backgroundColor: colors.softPanel,
    borderColor: colors.line,
    borderRadius: 8,
    borderWidth: 1,
    gap: 8,
    padding: 12,
  },
  teamName: {
    color: colors.ink,
    flex: 1,
    fontSize: 18,
    fontWeight: "900",
    marginBottom: 12,
  },
  teamOption: {
    alignItems: "center",
    backgroundColor: colors.softPanel,
    borderColor: "#dfe6ef",
    borderRadius: 8,
    borderWidth: 2,
    flexDirection: "row",
    gap: 7,
    minHeight: 42,
    paddingHorizontal: 10,
  },
  teamOptionCoins: {
    color: colors.info,
    fontSize: 12,
    fontWeight: "900",
  },
  teamOptionDot: {
    borderRadius: 5,
    height: 10,
    width: 10,
  },
  teamOptionText: {
    color: colors.ink,
    fontSize: 13,
    fontWeight: "800",
  },
  title: {
    color: colors.ink,
    fontSize: 27,
    fontWeight: "900",
    letterSpacing: 0,
  },
  titleBlock: {
    flex: 1,
    paddingRight: 12,
  },
});
