import { StyleSheet } from "react-native";

import { colors } from "@/utils/colors";

export const mapStyles = StyleSheet.create({
  actionLogContent: {
    gap: 8,
    paddingBottom: 2,
  },
  actionLogPanel: {
    backgroundColor: colors.panel,
    borderColor: colors.line,
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    gap: 10,
    minHeight: 0,
    padding: 14,
  },
  actionLogScroller: {
    flex: 1,
    minHeight: 0,
  },
  actionLogTitle: {
    color: colors.ink,
    flex: 1,
    fontSize: 16,
    fontWeight: "900",
  },
  challengeMarker: {
    alignItems: "center",
    borderColor: colors.panel,
    borderRadius: 15,
    borderWidth: 2,
    height: 30,
    justifyContent: "center",
    boxShadow: "0 2px 5px rgba(0, 0, 0, 0.2)",
    width: 30,
  },
  challengeMarkerText: {
    color: colors.panel,
    fontSize: 11,
    fontWeight: "900",
  },
  content: {
    flex: 1,
    overflow: "hidden",
    padding: 16,
  },
  desktopContent: {
    paddingHorizontal: 0,
    paddingRight: 12,
  },
  fitButton: {
    alignItems: "center",
    backgroundColor: colors.panel,
    borderColor: colors.lineStrong,
    borderRadius: 8,
    borderWidth: 1,
    height: 38,
    justifyContent: "center",
    position: "absolute",
    right: 10,
    top: 10,
    width: 38,
    zIndex: 8,
  },
  floatingButton: {
    alignItems: "center",
    backgroundColor: colors.panel,
    borderColor: colors.lineStrong,
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: "row",
    gap: 6,
    left: 10,
    minHeight: 38,
    paddingHorizontal: 10,
    position: "absolute",
    top: 10,
    zIndex: 8,
  },
  floatingButtonText: {
    color: colors.ink,
    fontSize: 12,
    fontWeight: "900",
  },
  frame: {
    alignSelf: "center",
    backgroundColor: "#d9e6f2",
    borderColor: "#c9d5e5",
    borderRadius: 8,
    borderWidth: 1,
    overflow: "hidden",
  },
  image: {
    left: 0,
    position: "absolute",
    top: 0,
  },
  inspectorContent: {
    gap: 10,
    paddingBottom: 4,
  },
  inspectorPanelWide: {
    flexShrink: 0,
    gap: 10,
  },
  inspectorScroller: {
    flex: 1,
  },
  inspectorShell: {
    flexShrink: 0,
    gap: 10,
    minHeight: 0,
    overflow: "hidden",
  },
  inspectorShellCompact: {
    height: 260,
  },
  inspectorShellWide: {
    alignSelf: "stretch",
    width: 360,
  },
  legendItem: {
    alignItems: "center",
    backgroundColor: colors.panel,
    borderColor: "#dfe6ef",
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: "row",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  legendOverlay: {
    backgroundColor: colors.panel,
    borderColor: colors.line,
    borderRadius: 8,
    borderWidth: 1,
    left: 10,
    maxWidth: "92%",
    padding: 8,
    position: "absolute",
    top: 56,
    zIndex: 8,
  },
  legendOverlayDesktop: {
    top: 10,
  },
  legendRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
    paddingRight: 16,
  },
  legendScroller: {
    flexGrow: 0,
    flexShrink: 0,
  },
  legendText: {
    color: colors.text,
    fontSize: 12,
    fontWeight: "700",
  },
  mainPane: {
    flex: 1,
    gap: 12,
    minHeight: 0,
    position: "relative",
  },
  markerSelected: {
    borderColor: colors.ink,
    borderWidth: 3,
    transform: [{ scale: 1.18 }],
  },
  markerSelectedTarget: {
    zIndex: 5,
  },
  markerTouchTarget: {
    alignItems: "center",
    height: 44,
    justifyContent: "center",
    marginLeft: -22,
    marginTop: -22,
    position: "absolute",
    width: 44,
  },
  mobileContent: {
    padding: 0,
  },
  mobileFrame: {
    borderRadius: 0,
    borderWidth: 0,
  },
  mobileInspectorGrip: {
    alignSelf: "center",
    backgroundColor: colors.lineStrong,
    borderRadius: 2,
    height: 4,
    marginBottom: 8,
    width: 40,
  },
  mobileInspectorHandle: {
    paddingHorizontal: 14,
    paddingTop: 8,
  },
  mobileInspectorHeader: {
    alignItems: "center",
    flexDirection: "row",
    gap: 10,
    paddingBottom: 8,
  },
  mobileInspectorSheet: {
    backgroundColor: colors.panel,
    borderColor: colors.line,
    borderRadius: 8,
    borderWidth: 1,
    bottom: 8,
    left: 8,
    overflow: "hidden",
    position: "absolute",
    right: 8,
    zIndex: 10,
  },
  mobileInspectorSheetCollapsed: {
    maxHeight: 148,
  },
  mobileInspectorSheetExpanded: {
    maxHeight: 390,
  },
  mobileInspectorSubtitle: {
    color: colors.textSoft,
    fontSize: 12,
    fontWeight: "800",
    marginTop: 2,
  },
  mobileInspectorTitle: {
    color: colors.ink,
    fontSize: 18,
    fontWeight: "900",
  },
  mobileMainPane: {
    gap: 0,
  },
  mobileViewport: {
    borderRadius: 0,
    borderWidth: 0,
    minHeight: 240,
  },
  mobileWorkspace: {
    gap: 0,
  },
  pickerOption: {
    alignItems: "center",
    backgroundColor: colors.softPanel,
    borderColor: colors.line,
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: "row",
    gap: 8,
    minHeight: 40,
    paddingHorizontal: 10,
  },
  pickerOptionSelected: {
    borderColor: colors.ink,
    borderWidth: 2,
  },
  pickerOptionText: {
    color: colors.ink,
    flex: 1,
    fontSize: 13,
    fontWeight: "800",
  },
  pickerPanel: {
    backgroundColor: colors.panel,
    borderColor: colors.line,
    borderRadius: 8,
    borderWidth: 1,
    gap: 8,
    marginBottom: 10,
    padding: 12,
  },
  pickerTitle: {
    color: colors.textSoft,
    fontSize: 12,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  stationMarker: {
    borderColor: colors.panel,
    borderRadius: 6,
    borderWidth: 2,
    height: 12,
    boxShadow: "0 2px 4px rgba(0, 0, 0, 0.22)",
    width: 12,
  },
  teamSummaryList: {
    gap: 8,
  },
  teamSummaryMeta: {
    color: colors.textSoft,
    fontSize: 12,
    fontWeight: "800",
  },
  teamSummaryName: {
    color: colors.ink,
    flex: 1,
    fontSize: 13,
    fontWeight: "900",
  },
  teamSummaryPanel: {
    backgroundColor: colors.panel,
    borderColor: colors.line,
    borderRadius: 8,
    borderWidth: 1,
    flexShrink: 0,
    gap: 12,
    marginBottom: 10,
    padding: 14,
  },
  teamSummaryRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
  },
  teamSummaryStatCell: {
    alignItems: "flex-end",
    minWidth: 58,
  },
  teamSummaryStatLabel: {
    color: colors.textSoft,
    fontSize: 10,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  teamSummaryStatValue: {
    color: colors.ink,
    fontSize: 14,
    fontWeight: "900",
  },
  teamSummaryTitle: {
    color: colors.ink,
    flex: 1,
    fontSize: 16,
    fontWeight: "900",
  },
  transformLayer: {
    alignSelf: "center",
  },
  viewport: {
    alignItems: "center",
    alignSelf: "center",
    backgroundColor: "#d9e6f2",
    borderColor: "#c9d5e5",
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    justifyContent: "center",
    minHeight: 180,
    overflow: "hidden",
    width: "100%",
  },
  viewportSlot: {
    flex: 1,
    minHeight: 0,
    position: "relative",
  },
  viewportTight: {
    backgroundColor: "transparent",
    borderWidth: 0,
  },
  workspace: {
    flex: 1,
    gap: 12,
    minHeight: 0,
    position: "relative",
  },
  workspaceWide: {
    flexDirection: "row",
  },
});
